[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "my-cool-django-app"
version = "42"
dependencies = [
	"django==5.0.6"
]

[project.optional-dependencies]
dev = ["pytest"]